### ISSUE TITLE
Convert IPv6 characters to uppercase

### ISSUE THREAD

**Issue by christopherbeneke** [cetteup/update-plex-ipv6-access-url#26]
I'm not sure if this is an issue for others, but on my plex server, if the IPv6 address portion of the custom server access URL isn't uppercase, my plex apps are not able to connect remotely.

For instance, my plex app fails to connect when the custom server access URL is formatted like this:
https://3210-488d-188f-5660-0000-0000-0000-9a52.f1c87d9690af4e0da1c2bfbf34b850fb.plex.direct:32400

But it works as expected when the URL is formatted like this:
https://3210-488D-188F-5660-0000-0000-0000-9A52.f1c87d9690af4e0da1c2bfbf34b850fb.plex.direct:32400

For reference, I am on Ubuntu 18.04 LTS using Plex Media Server version 1.40.0.7775

**Comment by christopherbeneke** [comment]
This comment on the plex forums is what gave me the idea to try using an upper-case IPv6 address even though the commenter is referring to this in the context of something called "myplex" which I am not familiar with.

https://forums.plex.tv/t/ipv6-support-for-myplex/36520/271

**Comment by cetteup** [comment]
Just to verify: When you are connecting remotely, do you actually see Plex connecting via the uppercase IPv6 access URL? You can test this by opening the dev tools in any browser and then navigating to Plex. The network tab will show you which URL Plex ends up using.

**Comment by christopherbeneke** [comment]
Chrome shows the shortened IPv6 address with lower-case characters.  I wish there was a way to check to see which access URL the Android Plex app is using.  Changing from upper-case to lower-case seems to have no effect on the behavior of the web app, it only seems to affect the Android app.

**Comment by cetteup** [comment]
You may be able to pull debug logs from the app, see https://support.plex.tv/articles/201573117-android-android-tv-fire-tv-logs/.

I just want to avoid that this is actually caused by something totally unrelated, since both IPv6 addresses and hostnames should be case-insensitive.

**Comment by christopherbeneke** [comment]
Thanks for sharing that, it's so helpful in troubleshooting this!

Here's something really strange.  When the custom server access URL is set to the uppercase format, the Android logs show that everything works as expected.

When the Custom server access URL is set to the lowecase format, the Android logs do not show any IPv6 address.  Instead the logs show two IPv4 addresses, one is the internal IP address of the server and the other is the public WAN IP address of my router.

This leads me to believe that for some reason Plex does not pass along the lowercase IPv6 address to the Android client.

I am actually observing something similar in the Roku app logs as well.  No IPv6 address shows up in the logs until the custom server access URL is set to uppercase.  It seems like this may be a bug in the way plex shares the custom access URL.  I am not sure why it doesn't seem to affect the web app when using plex.tv/web though.

**Comment by cetteup** [comment]
One last thing: What do you see in the logs when there's no IPv6 custom access URL configured? Same as when it's lowercase?

**Comment by cetteup** [comment]
I added a new flag. If you run with `-capitalization upper` it will convert the IPv6 IP address to uppercase when building the custom access URL.

Will publish a new release later today.

**Comment by cetteup** [comment]
Released as part of [0.2.0](https://github.com/cetteup/update-plex-ipv6-access-url/releases/tag/v0.2.0).

**Comment by christopherbeneke** [comment]
That seems to work perfectly, thank you and happy new year!
