### ISSUE TITLE
Running Script on Windows, Device "" does not exist

### ISSUE THREAD

**Issue by Axel-of-the-Key** [cetteup/update-plex-ipv6-access-url#39]
![image](https://github.com/cetteup/update-plex-ipv6-access-url/assets/8282745/6aade27a-d50c-4504-83cd-1c2f4b7889ac)
Attempting to run the script, I am given this error saying that device "" does not exist. Attempting to run with arguments attempts to use the first argument as a device name and similarly fails. Not sure if there is an additional argument I need to use because I am on Windows or not.

**Comment by cetteup** [comment]
Two things:
- You did not specify an interface to use, which is required with the legacy script.
- Any specific reason you are using the legacy script? I highly recommend you try/use the Go-based rewrite. You can download the latest release here https://github.com/cetteup/update-plex-ipv6-access-url/releases/tag/v0.3.0.

**Comment by Axel-of-the-Key** [comment]
Oh! Thanks for that. You can close this. XD
