### ISSUE TITLE
need enable Ipv6 flag ?

### ISSUE THREAD

**Issue by luoshuhui** [cetteup/update-plex-ipv6-access-url#42]
<connection protocol="http" address="240e-03a1-02f1-9f70-ca8a-d8ff-fe32-766b.6f704a12870b46dcad49b06b7d606f8b.plex.direct" port="32400" uri="http://240e-03a1-02f1-9f70-ca8a-d8ff-fe32-766b.6f704a12870b46dcad49b06b7d606f8b.plex.direct:32400" local="0" relay="0" IPv6="0"/>

connect  DTO，should enable Ipv6 flag?
<img width="1330" alt="截屏2024-09-30 10 40 37" src="https://github.com/user-attachments/assets/dea9bc1f-d114-4e8c-8537-19935837ba23">

**Comment by luoshuhui** [comment]
> connect DTO，should enable Ipv6 flag?

![Uploading 截屏2024-09-30 10.40.37.png…]()

**Comment by cetteup** [comment]
That flag is set by Plex internally and is only visible/present in the [resources list](https://support.plex.tv/articles/206721658-using-plex-tv-resources-information-to-troubleshoot-app-connections/). It saying `IPv6="0"` has no impact on the functionality of the custom access URL.
