### ISSUE TITLE
Multiple IP adresses on one interface

### ISSUE THREAD

**Issue by jbreitbart** [cetteup/update-plex-ipv6-access-url#5]
Hi

the network device that my plex server is using has multiple IP addresses. Is there a way to select a specific one (or add multiple URLs)?

**Comment by jbreitbart** [comment]
Thanks for the quick reply. I actually had to dig a bit into IPv6 to understand the different addresses myself. The device has 4 addresses:
* One is assigned by the router and is the public IPv6 address (which is the one that should be used for plex)
* One starts with fd98, which apparently is a Unique Local Unicast address
* One starts with fe80, which is a link local address
* One starts with fd00, which is a unique local unicast address

I am not sure why they are assigned the way they are, however for me it seems reasonable to ignore addresses that starts with an f and just use the first address to update the URL.

**Comment by cetteup** [comment]
Ah, I see. I thought your interface had multiple public IPv6 addresses.

The script should already ignore the local addresses. Have you tried running the "find ip" command once manually on your machine?
```sh
/sbin/ip -6 addr show dev [interface_name] scope global | grep inet6 | awk -F '[ \t]+|/' '{print $3}'
```
(replace `[interface_name]` with the actual name of the interface in question)

**Comment by jbreitbart** [comment]
```
$ /sbin/ip -6 addr show dev eno1 scope global | grep inet6 | awk -F '[ \t]+|/' '{print $3}'
fd98:b571:5846:4f05:f639:9ff:fe1a:f47c
fd00::f639:9ff:fe1a:f47c
2a03:7500:66f:xxxx:xxxx:xxxx:xxxx:xxxx
```
It only filters one address

**Comment by cetteup** [comment]
Ok. Could you run this once? I'd like to see what flags the addresses have ("scope", "global" etc.).

```sh
/sbin/ip -6 addr show dev eno1
```

**Comment by b1ggi** [comment]
Hi,

i can help you here with my example, its almost the same as jbreitbarts:

ip -6 addr show dev br0
3: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet6 2003:cf:bf34:db00:xxxx:xxxx:xxxx:xxxx/64 scope global temporary dynamic
       valid_lft 6765sec preferred_lft 1365sec
    inet6 2003:cf:bf34:db00:yyyy:yyyy:yyyy:yyyy/64 scope global temporary deprecated dynamic
       valid_lft 6765sec preferred_lft 0sec
    inet6 2003:cf:bf34:db00:zzzz:zzzz:zzzz:zzzz/64 scope global dynamic mngtmpaddr
       valid_lft 6765sec preferred_lft 1365sec
    inet6 fe80::ffff:ffff:ffff:ffff/64 scope link
       valid_lft forever preferred_lft forever


Running it through the script:

ip -6 addr show dev br0 scope global | grep inet6 | awk -F '[ \t]+|/' '{print $3}'
2003:cf:bf34:db00:xxxx:xxxx:xxxx:xxxx
2003:cf:bf34:db00:yyyy:yyyy:yyyy:yyyy
2003:cf:bf34:db00:zzzz:zzzz:zzzz:zzzz

The last one is my custom static ip configured through pre-up command tokens in /etc/network/interfaces, the 2 top ones are temporary ipv6 from the privacy extenstion

iface br0 inet6 auto
pre-up /sbin/ip token set ::zzzz:zzzz:zzzz:zzzz/64 dev br0
privext 2
dns-nameservers fd00::aaaa:aaaa:aaaa:aaaa

**Comment by cetteup** [comment]
I took a closer look at the options for `ip`. The `-o[neline}` brings all the additional attributes of the address into the same line, allowing us to filter based on them.

This should find your desired address:
```shell
/sbin/ip -6 -o addr show dev eth0 scope global | grep inet6 | grep -v deprecated | grep -v temporary | awk -F '[ \t]+|/' '{print $4}'
```

Let me know if it works for you. If so, I'll update the script accordingly.

**Comment by b1ggi** [comment]
i adapted to my br0 device, it works:

/sbin/ip -6 -o addr show dev br0 scope global | grep inet6 | grep -v deprecated | grep -v temporary | awk -F '[ \t]+|/' '{print $4}'
2003:cf:bf34:db00:zzzz:zzzz:zzzz:zzzz

**Comment by cetteup** [comment]
Fixed in the latest commit.

@jbreitbart If you are still facing issues with your setup, please re-open the issue.

**Comment by jbreitbart** [comment]
Thanks a lot for fixing this, and sorry that I vanished. The system was not online for quite a while and I didn't have time to complete the setup of my Plex server. However, I gave it a quick try and it seems to pick up the correct IP 👍
