### ISSUE TITLE
Does not resolve public IPv6 address

### ISSUE THREAD

**Issue by damianperera** [cetteup/update-plex-ipv6-access-url#9]
### Current Behaviour
Resolves the dynamic IPv6 address assigned by the local router.

### Expected Behaviour
Resolves the dynamic public IPv6 address assigned by the network provider.

### Suggestion
Fetch the public IPv6 address via https://ipv6.lafibre.info/ip.php

**Comment by cetteup** [comment]
I don't quite understand what is the issue here. Generally, the router assigns a "public" IPv6 IP to each device, which the script should grab.

What does your setup look like? Do you have multiple IPv6 addresses on the same network interface? Or some special routing setup where the IPv6 IP on the interface is different from the public one?

**Comment by damianperera** [comment]
My router has a public IPv6 from the ISP and issues an IPv4 to local network devices. The router doesn't assign a public IPv6 to local network devices.

**Comment by cetteup** [comment]
That's a bit of an odd setup, does your router allow you to configure this somehow?

Have you checked wether remote access via IPv6 works in scenario? Do you forward the port for IPv4 and IPv6?

**Comment by damianperera** [comment]
> does your router allow you to configure this somehow?

Unfortunately not.

> remote access via IPv6 works in scenario

Yep.

>  Do you forward the port for IPv4 and IPv6?

Port forwarding works by forwarding the port (`:32400`) to the MAC address of the device.

**Comment by cetteup** [comment]
I have an idea for how to address this, but I believe it only works if your local devices have an all IPv6 route to the internet. If your devices do not have any IPv6-based path to the internet, they should not even be able to connect to e.g. `api6.ipify.org`.

Does your router assign any IPv6 addresses to your client devices? Also, try running a trace to `api6.ipify.org` and see if that works.
